In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [23]:
iris = load_iris()

X = iris.data      # features
y = iris.target    # labels

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (150, 4)
Target shape: (150,)


In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (105, 4)
Testing data: (45, 4)


In [25]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!


In [26]:
y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc * 100, "%")

Accuracy: 100.0 %


In [27]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [28]:
new_flower = [[5.1, 3.5, 1.4, 0.2]]
result = model.predict(new_flower)

print("Predicted class:", iris.target_names[result][0])

Predicted class: setosa
